words = [
    "Jira",
    "aig",
    "auth",
    "buildx",
    "cass",
    "cmdline",
    "cqlsh",
    "cxeps",
    "devmode",
    "dtog",
    "duckdb",
    "graphviz",
    "icsv",
    "ijson",
    "itsv",
    "jmq",
    "jql",
    "limactl",
    "listparams",
    "mdelete",
    "mget",
    "mise",
    "mkdir",
    "murdoc",
    "nerdctl",
    "netrc",
    "nocheck",
    "nwise",
    "opprint",
    "pcre",
    "pgdatabase",
    "pghost",
    "pgurl",
    "pguser",
    "pgusername",
    "psql",
    "rclone",
    "rediscli",
    "scp",
    "scriptname",
    "sshto",
    "tojson",
    "wget",
    "worldbuilder",
    "zargs",
]
